[tool.poetry]
name = "crashreportimporter"
version = "0.0.1"
description = "NewPipe crash report importer"
authors = ["TheAssassin <theassassin@assassinate-you.net>"]
license = "MIT"
packages = [
    { include = "newpipe_crash_report_importer" },
]

[tool.poetry.dependencies]
python = "^3.6"
aiosmtpd = "^1.4.2"
bleach = "^3.2.3"
requests = "^2.25.1"
sentry-sdk = "^2.8.0"
aiohttp = {extras = ["speedups"], version = "^3.7.3"}
aiodns = "^3.2.0"
click = "^7.1.2"
coloredlogs = "^15.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
